[tool.taskipy.tasks]
run = 'fastapi dev challenge/app.py'
pre_test = 'task lint'
test = 'pytest --cov=challenge challenge/tests -vv'
post_test = 'coverage html'
lint = 'ruff check . && ruff check . --diff'
format = 'ruff check . --fix && ruff format .'

[tool.ruff]
line-length = 79
extend-exclude = ['migrations']
